/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_api_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/smoke/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Smoke Llm */
        post: operations["smoke_llm_api_smoke_llm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/smoke/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Smoke Search */
        post: operations["smoke_search_api_smoke_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/smoke/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Smoke Fetch */
        post: operations["smoke_fetch_api_smoke_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_api_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runtime */
        get: operations["get_runtime_api_runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trace */
        get: operations["get_trace_api_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Documents */
        get: operations["list_knowledge_documents_api_knowledge_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Document */
        get: operations["get_knowledge_document_api_knowledge_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Knowledge Document */
        delete: operations["delete_knowledge_document_api_knowledge_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/documents/{document_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Document Versions */
        get: operations["get_knowledge_document_versions_api_knowledge_documents__document_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/documents/{document_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff Knowledge Document */
        get: operations["diff_knowledge_document_api_knowledge_documents__document_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/documents/{document_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Knowledge Document Version */
        post: operations["merge_knowledge_document_version_api_knowledge_documents__document_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Knowledge */
        post: operations["search_knowledge_api_knowledge_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Presets */
        get: operations["list_knowledge_presets_api_knowledge_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Knowledge */
        post: operations["evaluate_knowledge_api_knowledge_eval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/eval/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Eval Runs */
        get: operations["list_knowledge_eval_runs_api_knowledge_eval_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/eval/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Eval Run */
        get: operations["get_knowledge_eval_run_api_knowledge_eval_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Stats */
        get: operations["get_knowledge_stats_api_knowledge_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/crawl-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Crawl Jobs */
        get: operations["list_knowledge_crawl_jobs_api_knowledge_crawl_jobs_get"];
        put?: never;
        /** Create Knowledge Crawl Job */
        post: operations["create_knowledge_crawl_job_api_knowledge_crawl_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/crawl-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Crawl Job */
        get: operations["get_knowledge_crawl_job_api_knowledge_crawl_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/crawl-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Crawl Runs */
        get: operations["list_knowledge_crawl_runs_api_knowledge_crawl_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Knowledge Batch */
        post: operations["create_knowledge_batch_api_knowledge_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/ingest-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Ingest Job */
        get: operations["get_knowledge_ingest_job_api_knowledge_ingest_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/ingest-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Ingest Jobs */
        get: operations["list_knowledge_ingest_jobs_api_knowledge_ingest_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Crawl Jobs */
        get: operations["list_crawl_jobs_api_crawl_jobs_get"];
        put?: never;
        /** Create Crawl Job */
        post: operations["create_crawl_job_api_crawl_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Crawl Sources */
        get: operations["list_crawl_sources_api_crawl_sources_get"];
        put?: never;
        /** Create Crawl Source */
        post: operations["create_crawl_source_api_crawl_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crawl Source */
        get: operations["get_crawl_source_api_crawl_sources__source_id__get"];
        put?: never;
        post?: never;
        /** Delete Crawl Source */
        delete: operations["delete_crawl_source_api_crawl_sources__source_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/sources/{source_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Crawl Source */
        post: operations["retry_crawl_source_api_crawl_sources__source_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/frontier/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crawl Frontier Stats */
        get: operations["get_crawl_frontier_stats_api_crawl_frontier_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crawl Job */
        get: operations["get_crawl_job_api_crawl_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Crawl Job */
        get: operations["stream_crawl_job_api_crawl_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisPlan */
        AnalysisPlan: {
            /** Topic */
            topic: string;
            /** Competitors */
            competitors: string[];
            /** Dimensions */
            dimensions: string[];
            /**
             * Complexity
             * @default medium
             * @enum {string}
             */
            complexity: "low" | "medium" | "high";
            /** Homepage Hints */
            homepage_hints?: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** BatchIngestItem */
        BatchIngestItem: {
            /**
             * Source
             * @enum {string}
             */
            source: "url" | "text" | "base64";
            /** Url */
            url?: string | null;
            /** Crawl Run Id */
            crawl_run_id?: string | null;
            /** Text */
            text?: string | null;
            /** Title */
            title?: string | null;
            /** Content B64 */
            content_b64?: string | null;
            /** Mime */
            mime?: string | null;
            /** Filename */
            filename?: string | null;
        };
        /** BatchIngestOptions */
        BatchIngestOptions: {
            /**
             * Max Concurrent
             * @default 4
             */
            max_concurrent: number;
            /**
             * Fail Fast
             * @default false
             */
            fail_fast: boolean;
        };
        /** BatchIngestRequest */
        BatchIngestRequest: {
            /** Items */
            items: components["schemas"]["BatchIngestItem"][];
            /**
             * @default {
             *       "max_concurrent": 4,
             *       "fail_fast": false
             *     }
             */
            options: components["schemas"]["BatchIngestOptions"];
        };
        /** BatchIngestResponse */
        BatchIngestResponse: {
            /** Job Id */
            job_id: string;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: components["schemas"]["RejectedItem"][];
        };
        /** ComparisonCell */
        ComparisonCell: {
            /** Competitor */
            competitor: string;
            /** Dimension */
            dimension: string;
            /** Value */
            value: string;
            /** Source Ids */
            source_ids?: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /** ComparisonMatrix */
        ComparisonMatrix: {
            /** Competitors */
            competitors: string[];
            /** Dimensions */
            dimensions: string[];
            /** Cells */
            cells?: components["schemas"]["ComparisonCell"][];
            /** Winner By Dimension */
            winner_by_dimension?: {
                [key: string]: string;
            };
            /** Summary */
            summary?: string[];
        };
        /** CompetitorCandidate */
        CompetitorCandidate: {
            /** Name */
            name: string;
            /** Rank */
            rank: number;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Evidence Titles */
            evidence_titles?: string[];
            /** Evidence Urls */
            evidence_urls?: string[];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
        };
        /** CompetitorDiscovery */
        CompetitorDiscovery: {
            /** Query */
            query: string;
            /** Candidates */
            candidates?: components["schemas"]["CompetitorCandidate"][];
            /** Selected Competitors */
            selected_competitors?: string[];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** CompetitorKB */
        CompetitorKB: {
            /** Competitor */
            competitor: string;
            /** Slices */
            slices?: {
                [key: string]: string[];
            };
            /** Sources */
            sources?: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /** CrawlFrontierStats */
        CrawlFrontierStats: {
            /**
             * Queued
             * @default 0
             */
            queued: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Cancelled
             * @default 0
             */
            cancelled: number;
        };
        /** CrawlJob */
        CrawlJob: {
            /** Id */
            id: string;
            /** Run Id */
            run_id?: string | null;
            /** Url */
            url: string;
            /** Competitor */
            competitor?: string | null;
            /** Dimension */
            dimension?: string | null;
            /** Status */
            status: string;
            /** Attempt Count */
            attempt_count: number;
            /** Error */
            error?: string | null;
            /**
             * Result Metadata
             * @default {}
             */
            result_metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CrawlJobCreate */
        CrawlJobCreate: {
            /** Url */
            url: string;
            /** Run Id */
            run_id?: string | null;
            /** Competitor */
            competitor?: string | null;
            /** Dimension */
            dimension?: string | null;
        };
        /** CrawlRunSummary */
        CrawlRunSummary: {
            /** Crawl Run Id */
            crawl_run_id: string;
            /** Doc Count */
            doc_count: number;
            /** Chunk Count */
            chunk_count: number;
            /** First Seen At */
            first_seen_at?: string | null;
            /** Last Seen At */
            last_seen_at?: string | null;
        };
        /** CrawlSource */
        CrawlSource: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "sitemap" | "rss" | "web_search" | "manual" | "pricing" | "official_docs" | "changelog" | "review_site";
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Competitor */
            competitor?: string | null;
            /** Dimension */
            dimension?: string | null;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CrawlSourceCreate */
        CrawlSourceCreate: {
            /**
             * Type
             * @enum {string}
             */
            type: "sitemap" | "rss" | "web_search" | "manual" | "pricing" | "official_docs" | "changelog" | "review_site";
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Competitor */
            competitor?: string | null;
            /** Dimension */
            dimension?: string | null;
            /** Priority */
            priority?: number | null;
        };
        /** CrawlSourceDetail */
        CrawlSourceDetail: {
            source: components["schemas"]["CrawlSource"];
            progress: components["schemas"]["CrawlFrontierStats"];
        };
        /** DocumentDiffResponse */
        DocumentDiffResponse: {
            /** Document Id */
            document_id: string;
            /** Against */
            against: string;
            /** Diff */
            diff: string[];
        };
        /** DocumentMergeRequest */
        DocumentMergeRequest: {
            /** Target Document Id */
            target_document_id: string;
        };
        /** EvalLabel */
        EvalLabel: {
            /** Query */
            query: string;
            /**
             * Relevant Doc Ids
             * @default []
             */
            relevant_doc_ids: string[];
            /**
             * Relevant Chunk Ids
             * @default []
             */
            relevant_chunk_ids: string[];
        };
        /** EvalRequest */
        EvalRequest: {
            /** Labels */
            labels: components["schemas"]["EvalLabel"][];
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            /** Preset */
            preset?: string | null;
        };
        /** EvalRunDetail */
        EvalRunDetail: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Top K */
            top_k: number;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Labels */
            labels: {
                [key: string]: unknown;
            }[];
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
        };
        /** EvalRunSummary */
        EvalRunSummary: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Top K */
            top_k: number;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
        /** FetchSmokeRequest */
        FetchSmokeRequest: {
            /**
             * Url
             * Format: uri
             * @default https://example.com
             */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warn" | "error";
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warn" | "error";
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Checks */
            checks?: components["schemas"]["HealthCheck"][];
        };
        /** HitlResumeRequest */
        HitlResumeRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "modify_plan" | "force_pass" | "redo";
            /** Note */
            note?: string | null;
            /** Dimensions */
            dimensions?: string[] | null;
        };
        /** IngestJob */
        IngestJob: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Total Items */
            total_items: number;
            /** Accepted Items */
            accepted_items: number;
            /** Completed Items */
            completed_items: number;
            /** Failed Items */
            failed_items: number;
            /** Rejected */
            rejected: {
                [key: string]: unknown;
            }[];
            /** Failed */
            failed: {
                [key: string]: unknown;
            }[];
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
            /** Options */
            options: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * KnowledgeDocument
         * @description A crawled or ingested document stored in the knowledge base.
         */
        KnowledgeDocument: {
            /** Id */
            id: string;
            /** Url */
            url?: string | null;
            /** Canonical Url */
            canonical_url?: string | null;
            /** Title */
            title: string;
            /** Source Type */
            source_type: string;
            /** Competitor */
            competitor?: string | null;
            /** Dimension */
            dimension?: string | null;
            /** Content Hash */
            content_hash: string;
            /** Text */
            text: string;
            /**
             * Markdown
             * @default
             */
            markdown: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Indexed At */
            indexed_at?: string | null;
            /** Last Seen At */
            last_seen_at?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Parent Document Id */
            parent_document_id?: string | null;
        };
        /** KnowledgeStatsResponse */
        KnowledgeStatsResponse: {
            /** Doc Count */
            doc_count: number;
            /** Chunk Count */
            chunk_count: number;
            /** Average Chunk Length */
            average_chunk_length: number;
            /** Source Breakdown */
            source_breakdown: {
                [key: string]: number;
            };
            /** Last 24H Ingest Count */
            last_24h_ingest_count: number;
            /** Fts Size */
            fts_size: number;
        };
        /** LlmSmokeRequest */
        LlmSmokeRequest: {
            /**
             * Prompt
             * @default Reply with exactly: ok
             */
            prompt: string;
        };
        /** QCIssue */
        QCIssue: {
            /** Id */
            id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn" | "blocker";
            /**
             * Detected By
             * @enum {string}
             */
            detected_by: "citation" | "consistency" | "coverage" | "schema" | "reflector";
            /** Target Agent */
            target_agent: string;
            /** Target Subagent */
            target_subagent?: string | null;
            /** Field Path */
            field_path: string;
            /** Problem */
            problem: string;
            redo_scope: components["schemas"]["RedoScope"];
            /**
             * Self Found
             * @default false
             */
            self_found: boolean;
        };
        /** RawSource */
        RawSource: {
            /** Id */
            id: string;
            /** Competitor */
            competitor: string;
            /** Covered Competitors */
            covered_competitors?: string[];
            /** Dimension */
            dimension: string;
            /** Source Type */
            source_type: string;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /**
             * Snippet
             * @default
             */
            snippet: string;
            /** Content Hash */
            content_hash: string;
            /** Confidence */
            confidence: number;
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at?: string;
        };
        /** RedoScope */
        RedoScope: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "writer_only" | "comparator" | "analyst" | "collector" | "full";
            /** Target Subagent */
            target_subagent?: string | null;
            /** Target Competitor */
            target_competitor?: string | null;
            /** Rationale */
            rationale: string;
        };
        /** ReflectionRecord */
        ReflectionRecord: {
            /** Iteration */
            iteration: number;
            /** Coverage Gaps */
            coverage_gaps?: string[];
            /** Confidence Outliers */
            confidence_outliers?: string[];
            /** Cross Competitor Gaps */
            cross_competitor_gaps?: string[];
            /** Suggested Redos */
            suggested_redos?: components["schemas"]["RedoScope"][];
        };
        /** RejectedItem */
        RejectedItem: {
            /** Index */
            index: number;
            /** Reason */
            reason: string;
        };
        /**
         * RetrievalHit
         * @description A single result from hybrid retrieval.
         */
        RetrievalHit: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Text */
            text: string;
            /** Score */
            score: number;
            /** Rerank Score */
            rerank_score?: number | null;
            /** Rerank Model */
            rerank_model?: string | null;
            /** Url */
            url?: string | null;
            /** Title */
            title?: string | null;
            /** Competitor */
            competitor?: string | null;
            /** Dimension */
            dimension?: string | null;
            /**
             * Source Type
             * @default
             */
            source_type: string;
            /**
             * Content Hash
             * @default
             */
            content_hash: string;
        };
        /** RetrievalPreset */
        RetrievalPreset: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Dense Weight */
            dense_weight: number;
            /** Sparse Weight */
            sparse_weight: number;
            /** Top K */
            top_k: number;
            /** Rerank Top K */
            rerank_top_k: number;
            /** Mmr Lambda */
            mmr_lambda: number;
            /** Query Rewrite Enabled */
            query_rewrite_enabled: boolean;
        };
        /** RetrievalRequest */
        RetrievalRequest: {
            /** Query */
            query: string;
            /** Preset */
            preset?: string | null;
            /**
             * Competitors
             * @default []
             */
            competitors: string[];
            /**
             * Dimensions
             * @default []
             */
            dimensions: string[];
            /**
             * Top K
             * @default 20
             */
            top_k: number;
            /**
             * Rerank Top K
             * @default 8
             */
            rerank_top_k: number;
            /**
             * Final Top K
             * @default 8
             */
            final_top_k: number;
            /**
             * Dense Weight
             * @default 1
             */
            dense_weight: number;
            /**
             * Sparse Weight
             * @default 1
             */
            sparse_weight: number;
            /**
             * Mmr Lambda
             * @default 0
             */
            mmr_lambda: number;
            /**
             * Enable Query Rewrite
             * @default true
             */
            enable_query_rewrite: boolean;
            /**
             * Num Rewrites
             * @default 3
             */
            num_rewrites: number;
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "dense" | "hybrid";
        };
        /** RetrievalResponse */
        RetrievalResponse: {
            /** Hits */
            hits: components["schemas"]["RetrievalHit"][];
            /** Query */
            query: string;
            /** Total */
            total: number;
        };
        /** RevisionRecord */
        RevisionRecord: {
            /** Id */
            id: string;
            /** Iteration */
            iteration: number;
            /** Stage */
            stage: string;
            /**
             * Before Md
             * @default
             */
            before_md: string;
            /**
             * After Md
             * @default
             */
            after_md: string;
            /** Issue Ids */
            issue_ids?: string[];
            /**
             * Issue Count Before
             * @default 0
             */
            issue_count_before: number;
            /**
             * Issue Count After
             * @default 0
             */
            issue_count_after: number;
            /**
             * Convergence Ratio
             * @default 1
             */
            convergence_ratio: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** RunCreateRequest */
        RunCreateRequest: {
            /** Topic */
            topic: string;
            /** Competitors */
            competitors?: string[];
            /** Dimensions */
            dimensions: string[];
            /**
             * Execution Mode
             * @default auto
             * @enum {string}
             */
            execution_mode: "auto" | "demo" | "real";
            /** Auto Redo Warn Enabled */
            auto_redo_warn_enabled?: boolean | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "interrupted" | "completed" | "failed";
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "demo" | "real";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            plan: components["schemas"]["AnalysisPlan"];
            /**
             * Max Iterations
             * @default 2
             */
            max_iterations: number;
            /**
             * Auto Redo Warn Enabled
             * @default false
             */
            auto_redo_warn_enabled: boolean;
            /**
             * Report Md
             * @default
             */
            report_md: string;
            /** Raw Sources */
            raw_sources?: components["schemas"]["RawSource"][];
            /** Competitor Kbs */
            competitor_kbs?: {
                [key: string]: components["schemas"]["CompetitorKB"];
            };
            competitor_discovery?: components["schemas"]["CompetitorDiscovery"] | null;
            comparison_matrix?: components["schemas"]["ComparisonMatrix"] | null;
            /** Qa Findings */
            qa_findings?: components["schemas"]["QCIssue"][];
            /** Reflections */
            reflections?: components["schemas"]["ReflectionRecord"][];
            /** Revisions */
            revisions?: components["schemas"]["RevisionRecord"][];
            /** Trace Spans */
            trace_spans?: components["schemas"]["TraceSpan"][];
            metrics?: components["schemas"]["RunMetrics"];
            /** Current Node */
            current_node?: string | null;
        };
        /** RunEvent */
        RunEvent: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "run_created" | "node_started" | "node_completed" | "interrupt" | "qa_issue" | "report_updated" | "revision_recorded" | "run_completed" | "run_failed";
            /** Agent */
            agent?: string | null;
            /** Subagent */
            subagent?: string | null;
            /** Swimlane */
            swimlane?: string | null;
            /** Message */
            message: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** RunMetrics */
        RunMetrics: {
            /**
             * Total Spans
             * @default 0
             */
            total_spans: number;
            /**
             * Total Duration Ms
             * @default 0
             */
            total_duration_ms: number;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Search Calls
             * @default 0
             */
            search_calls: number;
            /**
             * Fetch Calls
             * @default 0
             */
            fetch_calls: number;
            /**
             * Input Tokens Estimate
             * @default 0
             */
            input_tokens_estimate: number;
            /**
             * Output Tokens Estimate
             * @default 0
             */
            output_tokens_estimate: number;
            /**
             * Cost Estimate Usd
             * @default 0
             */
            cost_estimate_usd: number;
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "interrupted" | "completed" | "failed";
            /**
             * Execution Mode
             * @enum {string}
             */
            execution_mode: "demo" | "real";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RuntimeConfig */
        RuntimeConfig: {
            /**
             * Default Execution Mode
             * @enum {string}
             */
            default_execution_mode: "demo" | "real";
            /** Demo Mode */
            demo_mode: boolean;
            /** Has Ark Api Key */
            has_ark_api_key: boolean;
            /** Has Ark Model */
            has_ark_model: boolean;
            /** Ark Base Url */
            ark_base_url: string;
            /** Ark Model */
            ark_model?: string | null;
            /** Web Search Provider */
            web_search_provider: string;
            /** Has Web Search Key */
            has_web_search_key: boolean;
            /** Auto Redo Enabled */
            auto_redo_enabled: boolean;
            /** Auto Redo Warn Enabled */
            auto_redo_warn_enabled: boolean;
            /** Hitl Enabled */
            hitl_enabled: boolean;
            /** Hitl Timeout Seconds */
            hitl_timeout_seconds: number;
        };
        /** SearchSmokeRequest */
        SearchSmokeRequest: {
            /**
             * Query
             * @default AI coding assistant competitors
             */
            query: string;
            /**
             * Max Results
             * @default 3
             */
            max_results: number;
        };
        /** SkillOutputSpec */
        SkillOutputSpec: {
            /** Prefix */
            prefix: string;
            /**
             * Confidence Default
             * @default 0.8
             */
            confidence_default: number;
            /**
             * Confidence No Url
             * @default 0.5
             */
            confidence_no_url: number;
            /** Required Dimension */
            required_dimension: string;
        };
        /** SkillSpec */
        SkillSpec: {
            /** Name */
            name: string;
            /**
             * Subagent Class
             * @default GenericCollector
             */
            subagent_class: string;
            /** Description */
            description: string;
            /** Tools Allowlist */
            tools_allowlist: string[];
            /** Query Templates */
            query_templates: string[];
            /**
             * Max Turns
             * @default 6
             */
            max_turns: number;
            /** Source Type */
            source_type: string;
            output: components["schemas"]["SkillOutputSpec"];
        };
        /** SmokeResult */
        SmokeResult: {
            /**
             * Component
             * @enum {string}
             */
            component: "llm" | "search" | "fetch" | "minimal_run";
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** TraceSpan */
        TraceSpan: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "llm" | "search" | "fetch" | "tool";
            /** Agent */
            agent: string;
            /** Subagent */
            subagent?: string | null;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Model */
            model?: string | null;
            /** Provider */
            provider?: string | null;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Input Chars
             * @default 0
             */
            input_chars: number;
            /**
             * Output Chars
             * @default 0
             */
            output_chars: number;
            /**
             * Input Tokens Estimate
             * @default 0
             */
            input_tokens_estimate: number;
            /**
             * Output Tokens Estimate
             * @default 0
             */
            output_tokens_estimate: number;
            /**
             * Cost Estimate Usd
             * @default 0
             */
            cost_estimate_usd: number;
            /**
             * Input Preview
             * @default
             */
            input_preview: string;
            /**
             * Output Preview
             * @default
             */
            output_preview: string;
            /** Metadata */
            metadata?: {
                [key: string]: string | number | boolean | null;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HitlResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    smoke_llm_api_smoke_llm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmSmokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmokeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    smoke_search_api_smoke_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchSmokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmokeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    smoke_fetch_api_smoke_fetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchSmokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmokeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSpec"][];
                };
            };
        };
    };
    get_runtime_api_runtime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
        };
    };
    get_trace_api_runs__run_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_documents_api_knowledge_documents_get: {
        parameters: {
            query?: {
                competitor?: string | null;
                dimension?: string | null;
                source_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocument"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_document_api_knowledge_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_document_api_knowledge_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_document_versions_api_knowledge_documents__document_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocument"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_knowledge_document_api_knowledge_documents__document_id__diff_get: {
        parameters: {
            query: {
                against: string;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDiffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_knowledge_document_version_api_knowledge_documents__document_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentMergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_knowledge_api_knowledge_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_presets_api_knowledge_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalPreset"][];
                };
            };
        };
    };
    evaluate_knowledge_api_knowledge_eval_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_eval_runs_api_knowledge_eval_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_eval_run_api_knowledge_eval_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_stats_api_knowledge_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeStatsResponse"];
                };
            };
        };
    };
    list_knowledge_crawl_jobs_api_knowledge_crawl_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_knowledge_crawl_job_api_knowledge_crawl_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_crawl_job_api_knowledge_crawl_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_crawl_runs_api_knowledge_crawl_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunSummary"][];
                };
            };
        };
    };
    create_knowledge_batch_api_knowledge_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_ingest_job_api_knowledge_ingest_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_ingest_jobs_api_knowledge_ingest_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_crawl_jobs_api_crawl_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crawl_job_api_crawl_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_crawl_sources_api_crawl_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlSource"][];
                };
            };
        };
    };
    create_crawl_source_api_crawl_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlSourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlSourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawl_source_api_crawl_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlSourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_crawl_source_api_crawl_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_crawl_source_api_crawl_sources__source_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlSourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crawl_frontier_stats_api_crawl_frontier_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlFrontierStats"];
                };
            };
        };
    };
    get_crawl_job_api_crawl_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_crawl_job_api_crawl_jobs__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
