"""Compatibility exports for the canonical identity source resolver."""

from packages.identity.source_resolver import (
    ANY_SOURCE_TOKEN_RE,
    RAW_SOURCE_ALIASES_KEY,
    RUN_RAW_SOURCE_ID_KEY,
    SOURCE_TOKEN_RE,
    VALID_SOURCE_TOKEN_RE,
    SourceResolution,
    SourceResolutionIndex,
    SourceResolutionStatus,
    SourceTokenNormalization,
    build_source_reconciliation,
    dedupe_strings,
    evidence_by_source_token,
    evidence_source_tokens,
    is_valid_source_token,
    malformed_source_tokens,
    merge_evidence_source_metadata,
    merge_source_aliases,
    normalize_report_source_tokens,
    normalize_report_version_sources,
    normalize_source_token,
    raw_source_alias_metadata,
    resolve_source_token,
    source_token_alias_map,
    source_tokens,
    string_list,
)

__all__ = [
    "ANY_SOURCE_TOKEN_RE",
    "RAW_SOURCE_ALIASES_KEY",
    "RUN_RAW_SOURCE_ID_KEY",
    "SOURCE_TOKEN_RE",
    "VALID_SOURCE_TOKEN_RE",
    "SourceResolution",
    "SourceResolutionIndex",
    "SourceResolutionStatus",
    "SourceTokenNormalization",
    "build_source_reconciliation",
    "dedupe_strings",
    "evidence_by_source_token",
    "evidence_source_tokens",
    "is_valid_source_token",
    "malformed_source_tokens",
    "merge_evidence_source_metadata",
    "merge_source_aliases",
    "normalize_report_source_tokens",
    "normalize_report_version_sources",
    "normalize_source_token",
    "raw_source_alias_metadata",
    "resolve_source_token",
    "source_token_alias_map",
    "source_tokens",
    "string_list",
]
